# .yaml files in this directory are executed workflows:
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
# This workflow is triggered on pushes to non-main (or master) branches
# Builds and tests the app (just test)
name: Run Tests

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
on:
  push:
    # only non-main (and non-master) branches
    branches:
      - "**"
      - "!main"
      - "!master"

jobs:
  test:
    name: Run deno tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - uses: extractions/setup-just@v1

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Test deno code
        run: just test
